  version:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # important: fetch full history for tags

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get latest tag
        id: get_tag
        run: |
          tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $tag"
          echo "tag=${tag}" >> $GITHUB_OUTPUT

      - name: Create new tag
        id: tag
        run: |
          old_tag=${{ steps.get_tag.outputs.tag }}
          if [[ "$old_tag" == "" ]]; then
            new_tag="v0.1.0"
          else
            # bump patch version: v1.2.3 -> v1.2.4
            IFS='.' read -r -a parts <<< "${old_tag#v}"
            patch=$((parts[2]+1)
            new_tag="v${parts[0]}.${parts[1]}.$patch"
          fi
          git tag "$new_tag"
          git push origin "$new_tag"
